CREATE TABLE IF NOT EXISTS sensor_location (
    location_id INTEGER PRIMARY KEY,
    sensor_description TEXT,
    sensor_name TEXT,
    installation_date DATE,
    note TEXT,
    location_type TEXT,
    status TEXT,
    direction_1_label TEXT,
    direction_2_label TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS pedestrian_hourly_count (
    location_id INTEGER NOT NULL REFERENCES sensor_location(location_id),
    sensing_datetime TIMESTAMPTZ NOT NULL,
    direction_1_count INTEGER,
    direction_2_count INTEGER,
    total_count INTEGER NOT NULL,
    is_imputed BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (location_id, sensing_datetime)
);

CREATE INDEX IF NOT EXISTS idx_hourly_datetime
    ON pedestrian_hourly_count (sensing_datetime);

CREATE TABLE IF NOT EXISTS pedestrian_minute_count (
    sensing_datetime TIMESTAMPTZ NOT NULL,
    location_id INTEGER NOT NULL REFERENCES sensor_location(location_id),
    direction_1_count INTEGER,
    direction_2_count INTEGER,
    total_count INTEGER NOT NULL,
    is_imputed BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (sensing_datetime, location_id)
);

CREATE INDEX IF NOT EXISTS idx_minute_datetime
    ON pedestrian_minute_count (sensing_datetime);

CREATE TABLE IF NOT EXISTS theme (
    theme_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theme TEXT NOT NULL,
    sub_theme TEXT NOT NULL,
    UNIQUE (theme, sub_theme)
);

CREATE TABLE IF NOT EXISTS landmark_category (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theme_id INTEGER NOT NULL REFERENCES theme(theme_id),
    category_name TEXT NOT NULL,
    is_refuge BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS landmark (
    landmark_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER NOT NULL REFERENCES landmark_category(category_id),
    feature_name TEXT NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION
);

CREATE INDEX IF NOT EXISTS idx_landmark_category ON landmark (category_id);
CREATE INDEX IF NOT EXISTS idx_category_refuge ON landmark_category (is_refuge);
