-- ClearWay database schema (PostgreSQL / Amazon RDS)
-- Built directly from the confirmed ERD. Do not restructure without
-- re-running the normalization walkthrough this was checked against.
-
--   - AUTOINCREMENT / INTEGER PRIMARY KEY  -> GENERATED BY DEFAULT AS IDENTITY
--     (BY DEFAULT, not ALWAYS -- the landmark ingest script assigns its own
--     theme_id/category_id values up front so they stay stable across re-runs,
--     which ALWAYS forbids without an explicit OVERRIDING SYSTEM VALUE clause)
--   - TEXT datetime columns                -> TIMESTAMPTZ
--   - INTEGER 0/1 flags                    -> BOOLEAN
--   - PRAGMA foreign_keys ON               -> not needed, Postgres enforces FKs by default

-- ---------------------------------------------------------------------
-- Sensor metadata (occasional updates) -> US1.1, US1.2
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sensor_location (
    location_id         INTEGER PRIMARY KEY,       -- comes from source data, not generated
    sensor_description   TEXT,
    sensor_name           TEXT,
    installation_date     DATE,
    note                   TEXT,
    location_type          TEXT,      -- Indoor / Outdoor
    status                  TEXT,      -- 'A' = Active, etc.
    direction_1_label       TEXT,
    direction_2_label       TEXT,
    latitude                 DOUBLE PRECISION,
    longitude                DOUBLE PRECISION
);

-- ---------------------------------------------------------------------
-- Pedestrian counts, hourly (daily batch updates) -> US1.1
-- One row per sensor per hour. Composite key per ERD:
-- (location_id, sensing_datetime).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pedestrian_hourly_count (
    location_id        INTEGER NOT NULL REFERENCES sensor_location(location_id),
    sensing_datetime    TIMESTAMPTZ NOT NULL,   -- derived from Sensing_Date + HourDay
    direction_1_count    INTEGER,
    direction_2_count    INTEGER,
    total_count           INTEGER NOT NULL,
    is_imputed             BOOLEAN NOT NULL DEFAULT FALSE,  -- true if zero-filled for a gap
    PRIMARY KEY (location_id, sensing_datetime)
);

CREATE INDEX IF NOT EXISTS idx_hourly_datetime
    ON pedestrian_hourly_count (sensing_datetime);

-- ---------------------------------------------------------------------
-- Pedestrian counts, minute-level / near-real-time (~15 min updates) -> US1.2
-- Composite key per ERD: (sensing_datetime, location_id).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pedestrian_minute_count (
    sensing_datetime    TIMESTAMPTZ NOT NULL,
    location_id          INTEGER NOT NULL REFERENCES sensor_location(location_id),
    direction_1_count     INTEGER,
    direction_2_count     INTEGER,
    total_count            INTEGER NOT NULL,
    is_imputed              BOOLEAN NOT NULL DEFAULT FALSE,  -- true if zero-filled (no reading = 0, not missing)
    PRIMARY KEY (sensing_datetime, location_id)
);

CREATE INDEX IF NOT EXISTS idx_minute_datetime
    ON pedestrian_minute_count (sensing_datetime);

-- ---------------------------------------------------------------------
-- Landmarks, three-tier theme -> category -> landmark (occasional
-- updates) -> US2.1. Split fixes the transitive dependency
-- (category_id -> theme -> sub_theme) found in the template's
-- normalization example.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS theme (
    theme_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theme         TEXT NOT NULL,
    sub_theme      TEXT NOT NULL,
    UNIQUE (theme, sub_theme)
);

CREATE TABLE IF NOT EXISTS landmark_category (
    category_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theme_id         INTEGER NOT NULL REFERENCES theme(theme_id),
    category_name     TEXT NOT NULL,   -- user-facing filter label
    is_refuge          BOOLEAN NOT NULL DEFAULT FALSE  -- explicit US2.1 allow-list flag
);

CREATE TABLE IF NOT EXISTS landmark (
    landmark_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     INTEGER NOT NULL REFERENCES landmark_category(category_id),
    feature_name      TEXT NOT NULL,
    latitude           DOUBLE PRECISION,
    longitude          DOUBLE PRECISION
);

CREATE INDEX IF NOT EXISTS idx_landmark_category ON landmark (category_id);
CREATE INDEX IF NOT EXISTS idx_category_refuge ON landmark_category (is_refuge);